// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"costa92/gin-wire/config"
	"costa92/gin-wire/routers"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *config.Configuration, logger *zap.Logger) (*App, func(), error) {
	engine := routers.NewRouter(configuration)
	server := newHttpServer(configuration, engine)
	app := newApp(configuration, logger, server)
	return app, func() {
	}, nil
}
